name: Java CI with Gradle

concurrency:
  group: "build-1.20.2"
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Remove *-dev.jar
        run: rm ./build/libs/*-dev.jar || true
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.20.2-build-${{ github.run_number }}"
          prerelease: false
          title: "1.20.2 Build ${{ github.run_number }}"
          files: |
            ./build/libs/*.jar